name: Trigger Lit Contracts

on:
  push:
    branches:
      - main

jobs:
  trigger-lit-contracts:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Lit Contracts Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/LIT-Protocol/lit-contracts/dispatches \
          -d '{"event_type":"sync_trigger"}'
